let dark_background = 1

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                               Plugin Settings                               "
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set runtimepath^=~/.config/nvim

" Enable plugins
call plug#begin()

" Editing
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'SirVer/ultisnips', { 'on': [] }
Plug 'ervandew/supertab'
Plug 'honza/vim-snippets'
Plug 'junegunn/vim-easy-align'
Plug 'scrooloose/nerdcommenter'

" Objects
Plug 'kana/vim-textobj-user'
Plug 'bps/vim-textobj-python'
Plug 'michaeljsmith/vim-indent-object'
Plug 'vim-scripts/argtextobj.vim'

" Motions
Plug 'easymotion/vim-easymotion'
Plug 'ggVGc/vim-fuzzysearch'
" Plug 'justinmk/vim-sneak'
Plug 'vim-scripts/ctags.vim'

" Utilities
Plug 'Shougo/vimproc', {'do' : 'make'}
Plug 'christoomey/vim-tmux-navigator'
Plug 'jpalardy/vim-slime'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
"Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'scrooloose/nerdtree'
Plug 'tmux-plugins/vim-tmux-focus-events'
Plug 'tomtom/tlib_vim'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'w0rp/ale'

" Visualisation
Plug 'airblade/vim-gitgutter'
Plug 'drewtempelmeyer/palenight.vim' " Use with whimsy.itermcolors
Plug 'itchyny/lightline.vim'
Plug 'junegunn/rainbow_parentheses.vim'
Plug 'plasticboy/vim-markdown'
Plug 'tpope/vim-surround'
Plug 'vim-scripts/textutil.vim'

" Clojure
Plug 'eraserhd/parinfer-rust'
Plug 'guns/vim-clojure-highlight'
Plug 'guns/vim-clojure-static'
Plug 'tpope/vim-fireplace'

" Haskell
Plug 'alx741/vim-hindent'
Plug 'nbouscal/vim-stylish-haskell'
Plug 'neovimhaskell/haskell-vim'
Plug 'parsonsmatt/intero-neovim'

" Python
Plug 'Shougo/echodoc.vim'
Plug 'Vimjas/vim-python-pep8-indent'
Plug 'manicmaniac/coconut.vim'
Plug 'zchee/deoplete-jedi'

" R
Plug 'jalvesaq/Nvim-R'

" Scala
Plug 'derekwyatt/vim-scala'

" Docker
Plug 'ekalinin/Dockerfile.vim'

" Racket
Plug 'wlangstroth/vim-racket'
"Plug 'MicahElliott/vrod'
"Plug 'guns/vim-sexp'
"Plug 'tpope/vim-sexp-mappings-for-regular-people'

" F#
Plug 'fsharp/vim-fsharp', {
      \ 'for': 'fsharp',
      \ 'do':  'make fsautocomplete',
      \}
Plug 'callmekohei/deoplete-fsharp', { 'do': 'bash install.bash' }

" HTML
Plug 'mattn/emmet-vim'

if has("unix")
  let s:uname = system("uname")
  if s:uname == "Darwin\n"
        Plug 'junegunn/vim-xmark', { 'do': 'make' }
  endif
endif

" Add plugins to &runtimepath
call plug#end()

" Lazy loading for UltiSnips
augroup load_ultisnips
  autocmd!
  autocmd InsertEnter * call plug#load('ultisnips') | autocmd! load_ultisnips
augroup END

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                            Vim General Settings                             "
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Set the leader to comma
let mapleader = ","

" Makes copy and pasting work
set clipboard=unnamed
set clipboard+=unnamedplus

" One tab equals to four spaces
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Use multiple of shiftwidth when indenting with '<' and '>'
set shiftround

" Expand tab to spaces
set expandtab

" Search case insensitive when all characters are lower case
set ignorecase
set smartcase

" Does not release visual mode during block indentation
vnoremap < <gv
vnoremap > >gv

" No more weird characters when pressing <Esc>
set ttimeout
set ttimeoutlen=0

" Faster scrolling
set ttyfast

" Enable omnicompletion
filetype plugin on
set omnifunc=syntaxcomplete#Complete

" Enable syntax highlighting
syntax on
filetype plugin indent on

" This does not seem to work with NeoVim
" For tmux colour compatibility
if has('vim')
    set term=screen-256color
endif

" Disable folding so that the key 'f' can be used for movement
set nofoldenable

" The bells can be distracting in OSX
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

" Gets rid of weird character in new GNOME terminal
if has("unix")
  let s:uname = system("uname")
  if s:uname == "Linux\n"
        set novisualbell
  endif
endif

" More line buffer
set so=3

" Better copy and paste
set pastetoggle=<F2>

" Mouse and backspace
set mouse=a
set bs=2

" Showing line numbers and length
set number
set relativenumber
set fo-=t

" Useful settings
set history=700
set undolevels=700

" Disable stupid backup and swap files - they trigger too many events
" for file system watchers
set nobackup
set nowritebackup
set noswapfile

" Tab management
set splitright
set splitbelow

" Live substitute preview
 if has('nvim')
     set inccommand=nosplit
 endif

" No redundant info
set noshowmode

" Sign column shows up all the time
set signcolumn=yes

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                                Colour Scheme                                "
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" It looks nicer in some colour schemes
if dark_background
    set background=dark
    "silent! colorscheme palenight
    silent! colorscheme monokai
    let g:palenight_terminal_italics=1
    hi Normal  guibg=NONE ctermbg=NONE
    hi LineNr  guibg=NONE ctermbg=NONE
    hi NonText guibg=NONE ctermbg=NONE
else
    silent! colorscheme akk_light
endif

if (has("nvim"))
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif

if (has("termguicolors"))
  set termguicolors
endif

" This is needed to make Airline work
set laststatus=2

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                                Vim Bindings                                 "
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Jump to escape mode
inoremap hh <Esc>
inoremap thhh th<Esc>
inoremap jj <Esc>
tnoremap <Esc> <C-\><C-n>

" Moving up and down physical lines
nnoremap j gj
nnoremap k gk

" Page up and down, then centers the cursor
noremap <C-u> <S-Up>zz
noremap <C-d> <S-Down>zz

" Jump to next method
nmap }} ]m
nmap {{ [m

" Centers screen whenever a search is found
nnoremap G Gzz
nnoremap n nzz
nnoremap N Nzz

" Since <C-a> is the Tmux prefix, we replace <C-a> with <C-o>
inoremap <C-o> <C-a>

" Repeat dot on multiple lines
vnoremap . :normal .<CR>

" Adds numbered jumps to jump list
nnoremap <expr> k (v:count > 1 ? "m'" . v:count : '') . 'k'
nnoremap <expr> j (v:count > 1 ? "m'" . v:count : '') . 'j'

" Make Ctrl-e jump to the end of the current line in the insert mode. This is
" handy when you are in the middle of a line and would like to go to its end
" without switching to the normal mode.
inoremap <C-e> <C-o>$

" Jumping between tabs
nnoremap ( :tabprevious<CR>
nnoremap ) :tabnext<CR>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                                Generic Autos                                "
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

autocmd BufNewFile,BufRead *.clj set filetype=clojure
autocmd BufNewFile,BufRead *.cu set ft=cu
autocmd BufNewFile,BufRead *.cuh set ft=cu
autocmd BufRead,BufNewFile *.md setfiletype markdown
autocmd BufRead,BufNewFile *.sc setfiletype scala

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                                   Plugins                                   "
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Lightline
let g:lightline = {
      \ 'colorscheme': 'one',
      \ }

" Tmux Navigator
if exists('$TMUX')
    function! TmuxOrSplitSwitch(wincmd, tmuxdir)
    let previous_winnr = winnr()
    silent! execute "wincmd " . a:wincmd
    if previous_winnr == winnr()
        call system("tmux select-pane -" . a:tmuxdir)
        redraw!
    endif
    endfunction

    let previous_title = substitute(system("tmux display-message -p '#{pane_title}'"), '\n', '', '')
    let &t_ti = "\<Esc>]2;vim\<Esc>\\" . &t_ti
    let &t_te = "\<Esc>]2;". previous_title . "\<Esc>\\" . &t_te

    nnoremap <silent> <C-h> :call TmuxOrSplitSwitch('h', 'L')<cr>
    nnoremap <silent> <C-j> :call TmuxOrSplitSwitch('j', 'D')<cr>
    nnoremap <silent> <C-k> :call TmuxOrSplitSwitch('k', 'U')<cr>
    nnoremap <silent> <C-l> :call TmuxOrSplitSwitch('l', 'R')<cr>
    tnoremap <silent> <C-h> <C-\><C-n>:call TmuxOrSplitSwitch('h', 'L')<cr>
    tnoremap <silent> <C-j> <C-\><C-n>:call TmuxOrSplitSwitch('j', 'D')<cr>
    tnoremap <silent> <C-k> <C-\><C-n>:call TmuxOrSplitSwitch('k', 'U')<cr>
    tnoremap <silent> <C-l> <C-\><C-n>:call TmuxOrSplitSwitch('l', 'R')<cr>
else
    map <C-h> <C-w>h
    map <C-j> <C-w>j
    map <C-k> <C-w>k
    map <C-l> <C-w>l
endif

" Airline
let g:airline_theme = 'distinguished'
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
let g:airline_left_sep = '»'
let g:airline_right_sep = '«'
let g:airline_mode_map = {
    \ '__' : '-',
    \ 'n'  : 'N',
    \ 'i'  : 'I',
    \ 'R'  : 'R',
    \ 'c'  : 'C',
    \ 'v'  : 'V',
    \ 'V'  : 'V',
    \ '' : 'V',
    \ 's'  : 'S',
    \ 'S'  : 'S',
    \ '' : 'S',
    \ }
let g:airline_section_y = ''

" Ale
let g:ale_linters = {
    \ 'python': ['pyflakes', 'mypy'],
    \ 'scala': ['scalastyle'],
    \ 'haskell': ['stack-ghc-mod', 'hlint']
    \ }
let g:ale_python_mypy_options = "–ignore-missing-imports"
let g:ale_linters_explicit = 1
let g:ale_completion_enabled = 1
let g:ale_sign_error = '>>'
let g:ale_sign_warning = '!!'
hi ALEErrorSign   ctermbg=234         ctermfg=9  guibg=234 guifg=9
hi ALEWarningSign ctermbg=234         ctermfg=11 guibg=234 guifg=11
hi ALEWarning     ctermbg=DarkMagenta guibg=DarkMagenta
let g:airline#extensions#ale#enabled = 1

" NERDCommenter
let g:NERDCreateDefaultMappings = 0
nmap <Space>c <Plug>NERDCommenterToggle
vmap <Space>c <Plug>NERDCommenterToggle
nmap gcc <Plug>NERDCommenterToggle
vmap gcc <Plug>NERDCommenterToggle

" SuperTab
let g:SuperTabDefaultCompletionType = "<c-n>"

" EasyMotion
let g:EasyMotion_smartcase = 1
let g:EasyMotion_keys = "aoeui'l;z,rqv.cjwyfxbdhtns"

" FuzzySearch
let g:fzf_action = {
            \'enter': 'tabedit',
            \'ctrl-v': 'vsplit',
            \'ctrl-t': 'tabedit'}

" Easy Align
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)

" UltiSnips
let g:UltiSnipsExpandTrigger = "<Tab>"
let g:UltiSnipsJumpForwardTrigger = "<C-b>"
let g:UltiSnipsJumpBackwardTrigger = "<C-z>"
let g:UltiSnipsSnippetDirectories = ["UltiSnips", "custom_snippets"]

" Easy-Align
nmap <Space>= V}oga*=<CR>

" Deoplete
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources = {}
let g:deoplete#sources.scala = ['buffer', 'tags', 'omni']
let g:deoplete#omni#input_patterns = {}
let g:deoplete#omni#input_patterns.scala = ['[^. *\t0-9]\.\w*',': [A-Z]\w', '[\[\t\( ][A-Za-z]\w*']
let g:deoplete#sources#jedi#server_timeout = 60
call deoplete#custom#option({
  \ 'auto_complete_delay': 0,
  \ 'ignore_case': v:true,
  \ 'refresh_always': v:false,
\ })

" Deoplete-Jedi
highlight Pmenu ctermbg=8 guibg=#606060
highlight PmenuSel ctermbg=1 guifg=#dddd00 guibg=#1f82cd
highlight PmenuSbar ctermbg=0 guibg=#d6d6d6

" Ctags
set tags=./tags;/

" Coconut
autocmd FileType coconut setlocal commentstring=#\ %s

" Parinfer
let g:parinfer_mode = 'smart'
let g:parinfer_enabled = 1
let g:parinfer_force_balance = 0

" Haskell - Taken from: https://blog.jez.io/haskell-development-with-neovim/
let g:haskell_indent_before_where = 2
let g:haskell_indent_case_alternative = 1
let g:haskell_indent_if = 2
let g:haskell_indent_let_no_in = 0
let g:hindent_line_length = 90
let g:hindent_on_save = 0
let g:intero_start_immediately = 1
let g:intero_type_on_hover = 1
let g:intero_use_neomake = 0
let g:intero_vertical_split = 1
let g:intero_window_size = 8
set updatetime=100

" FSharp
let g:fsharp_map_keys = 0

" Slime
let g:slime_target = "tmux"
silent! let g:slime_default_config = {
    \ "socket_name": split($TMUX, ",")[0],
    \ "target_pane": ":0.1"
    \ }
let g:slime_dont_ask_default = 1
let g:slime_python_ipython = 1

" Echodoc
let g:echodoc_enable_at_startup = 1

" Rainbow Parantheses
augroup rainbow_lisp
  autocmd!
  autocmd FileType lisp,clojure,scheme RainbowParentheses
augroup END

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                           Leader + Space Remaps                             "
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Turning off highlights (after searching)
nnoremap <Space>nh :nohlsearch<CR>

" Close current tab
nnoremap <Space>eq :q<CR>

" Tabs (misnamed as buffers)
nnoremap <Space>be :FZF<CR>
nnoremap <Space>bh :FZF ~<CR>
nnoremap <Space>bj :NERDTreeToggle<CR>
nnoremap <Space>bn :tabnext<CR>
nnoremap <Space>bp :tabprevious<CR>
nnoremap <Space>bs :update<CR>
nnoremap <Space>bx :q<CR>
if !exists('g:lasttab')
  let g:lasttab = 1
endif
nnoremap <Space>bb :exe "tabn ".g:lasttab<CR>
au TabLeave * let g:lasttab = tabpagenr()

" Remove trailing whitespace
nnoremap <silent> <Space>rw :keeppatterns %s/\s\+$//<CR>

" Shortuct to reload vimrc
nmap <Space>rv :so ~/.config/nvim/init.vim<CR>:echo '.nvimrc reloaded!'<CR>

" Panes
nnoremap <Space>ah :split<CR>
nnoremap <Space>av :vsplit<CR>
nnoremap <Space>ax :q<CR>

" Copy the entire script to the clipboard, to top and to bottom
nnoremap <Space>ya mwggVG"+y'wzz
nnoremap <Space>yk mwggV'w"+y'wzz
nnoremap <Space>yj mwGV'w"+y'wzz

" Map sort function to a key
vnoremap <Space>s :sort<CR>

" Switch back and forth between relative and absolute number
nnoremap <Space>rn :set relativenumber!<CR>

" Git
nnoremap <Space>gg :GitGutter<CR>
nnoremap <Space>gd :Gdiff<CR>
nnoremap <Space>gb :Gblame<CR>

" Jumps
" This is to get rid of awful <Leader><Leader> default
map <Space><Space>em <Plug>(easymotion-prefix)
nmap <Space><Space> <Plug>(easymotion-s)
vmap <Space><Space> <Plug>(easymotion-s)

" Tags
nnoremap <Space>j :Tag<CR>

" Fold Toggle
" nnoremap <Leader>f za
" nnoremap <Leader>df zE
" nnoremap <Leader>} zfa}
