FROM continuumio/miniconda3:4.5.4

MAINTAINER Anthony Khong <anthony.kusumo.khong@gmail.com>

ENV USER root
ENV HOME /root
ENV TERM screen-256color
ENV PYTHONPATH /root
WORKDIR /root
ENTRYPOINT /bin/bash

RUN apt-get update && apt-get install -y build-essential

RUN conda install -y python=3.7 anaconda && pip install --upgrade pip

ADD docker/requirements-ml-dev.txt /opt/requirements.txt

RUN pip install -r /opt/requirements.txt

RUN export PYTHONPATH="${PYTHONPATH}:/root"
