#!/bin/bash
# Sources:
# - https://vishnudevtj.github.io/notes/rsync
# - https://unix.stackexchange.com/a/42292

set -euo pipefail

print_help() {
    echo "Detects changes in the current directory, and syncs to a destination."
    echo "Note: does not detect new files and ignores files according to .gitignore!"
    echo -e
    echo "Usage: auto-sync --destination DEST [--port PORT]"
    echo -e
    echo "Options"
    echo -e "--destination:\trsync's destination"
    exit 1
}

port=22
destination=null
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        --destination)
            destination="$2"
            shift
            shift
            ;;
        --port)
            port="$2"
            shift
            shift
            ;;
        --help)
            print_help
            shift
            ;;
        *)
            echo "Unrecognised option!"
            echo -e
            print_help
            exit 1
    esac
done

cleanup () {
    kill -s SIGTERM $!
    exit 0
}

trap cleanup SIGINT SIGTERM


if [[ "$destination" = null ]]; then
    echo "Destination must be set!"
    echo -e
    print_help
    exit 1
else
    while true ;do \
        sleep 2s;
        find . -not -path "./.git*" | \
            entr -d \
                rsync -avz \
                    -e "ssh -p $port" \
                    --filter=':- .gitignore' \
                    --exclude='.git/' \
                    --max-size=1.0m \
                    . "$destination";
    done
fi
