#!/bin/bash

# References:
# - https://gist.github.com/JohannesBuchner/62fc88277709bb29f9e7
# - https://unix.stackexchange.com/questions/50508/reusing-ssh-session-for-repeated-rsync-commands

set -euo pipefail

print_help() {
    echo "$(basename "$0") [--help] [(--source) --remote (--port) --destination]"
    echo "Syncs a source directory to a remote destination, watches the source directory for changes, then resyncs."
    echo
    echo "Options:"
    echo "--help            prints this help message."
    echo "--source          the source directory to be synced."
    echo "--remote          the remote machine to sync to."
    echo "--port            the SSH port to establish connection to the remote machine."
    echo "--destination     the destination directory on the remote machine."
    echo
    echo "Example:"
    echo "auto-sync --source ~/repo-name --remote user@server_ip"
    echo "auto-sync --source ~/dir0/dir1 --remote user@server_ip --port 22 --destination \"~/dir0\""
    echo
    exit 0
}

remote=null
port=22
src=$PWD
destination="~"
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        --source)
            src="$2"
            shift
            shift
            ;;
        --remote)
            remote="$2"
            shift
            shift
            ;;
        --port)
            port="$2"
            shift
            shift
            ;;
        --destination)
            destination="$2"
            shift
            shift
            ;;
        --help)
            print_help
            shift
            ;;
        *)
            echo "Unrecognised option!"
            echo -e
            print_help
            exit 1
    esac
done

if [[ "$remote" = null ]]; then
    echo "Remote hostname or IP address must be set!"
    echo -e
    print_help
    exit 1
fi

control_dir="$HOME/.ssh/auto-sync/"
control_path="$control_dir/%L-%r@%h:%p"
setup-master-ssh-connection() {
    echo "$(date -u) | Setting up master SSH connection ..."
    mkdir -p $control_dir
    ssh -nNf \
        -o ControlMaster=yes \
        -o ControlPath=$control_path \
        -p $port \
        $remote
}

sync() {
    echo "$(date -u) | Syncing files ..."
    rsync -avz \
        -e "ssh -o 'ControlPath=$control_path' \
        -p $port" \
        --filter=':- .gitignore' \
        --exclude='.git/' \
        --max-size=1.0m \
        $src "$remote:$destination";
    echo "$(date -u) | Watching for changes ..."
}

exit-master-ssh-connection() {
    echo "$(date -u) | Exiting master SSH connection ..."
    control_path=$(find $control_dir -name "*$remote:$port")
    ssh -S $control_path \
        -O exit \
        -p $port \
        $remote
}

cleanup () {
    exit-master-ssh-connection
    exit 0
}
trap cleanup SIGINT SIGTERM

setup-master-ssh-connection
sync
fswatch -r . | while read file event; do sync; done
