#!/bin/bash
# Source: https://gist.github.com/JohannesBuchner/62fc88277709bb29f9e7

set -euo pipefail

cleanup () {
    kill -s SIGTERM $!
    exit 0
}
trap cleanup SIGINT SIGTERM

sync() {
    echo "$(date) --- syncing ..."
    rsync -avz \
        -e "ssh -p $port" \
        --filter=':- .gitignore' \
        --exclude='.git/' \
        --max-size=1.0m \
        . "$destination";
    echo "$(date) --- watching ..."
}

port=22
destination=null
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        --destination)
            destination="$2"
            shift
            shift
            ;;
        --port)
            port="$2"
            shift
            shift
            ;;
        --help)
            print_help
            shift
            ;;
        *)
            echo "Unrecognised option!"
            echo -e
            print_help
            exit 1
    esac
done

if [[ "$destination" = null ]]; then
    echo "Destination must be set!"
    echo -e
    print_help
    exit 1
fi

sync
fswatch -r . | while read file event; do sync; done
