# Terminal colouring
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'

export PATH="/Users/akkhong:$PATH"
export PATH="/Users/akkhong/.local/bin:$PATH"
export PATH="/opt/anaconda/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/opt/spark/bin:$PATH"
export DYLD_FALLBACK_LIBRARY_PATH=/usr/local/opt/openblas/lib/libopenblasp-r0.2.15.dylib:$DYLD_FALLBACK_LIBRARY_PATH
export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:/Users/akkhong/anaconda/lib

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

source ~/dotfiles/bash/bash_shortcuts
source ~/dotfiles/bash/bash_preferences
if [ -d /Users/akkhong/torch ]; then
    . /Users/akkhong/torch/install/bin/torch-activate
fi

# Vagrant 
function vzb() {
    vagrant up;
    zb "$1"
}

function zb() {
    sbt researchfw/prod:"deploy-notebook --conf prod akhong/$1"
}

function runners() {
    cd researchfw/src/main/scala/com/agoda/ml/research/deploy/runners
}

function runners_test() {
    cd researchfw/src/test/scala/com/agoda/ml/research/deploy
}

function trivago_bidder() {
    cd /Users/akhong/repos/trivago/trivago_bidder/src/main/scala/com/agoda/mse/trivago/allocator
}
