# Terminal colouring
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'

# added by Anaconda 2.3.0 installer
export PATH="//anaconda/bin:$PATH"
export DYLD_FALLBACK_LIBRARY_PATH=/usr/local/opt/openblas/lib/libopenblasp-r0.2.15.dylib:$DYLD_FALLBACK_LIBRARY_PATH
export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:/Users/akkhong/anaconda/lib
export PYTHONPATH=$PYTHONPATH:/Users/akkhong/cmls

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

source ~/dotfiles/bash/bash_shortcuts
source ~/dotfiles/bash/bash_preferences
