# Terminal colouring
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'

export PATH="$HOME:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export DOCKER_DEFAULT_PLATFORM=linux/amd64

source ~/dotfiles/bash/bash_shortcuts.sh
source ~/dotfiles/bash/bash_preferences.sh
source ~/dotfiles/google_cloud/bash_gcp.sh
source ~/dotfiles/aws/bash_aws.sh

export SCREEN=xterm-256color
export IP=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')

alias rosetta-brew='arch -x86_64 /usr/local/bin/brew'

if command -v terraform &> /dev/null
then
    complete -C /usr/local/bin/terraform terraform
fi
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

export DARK_VIM=1
export PATH="$PATH:/opt/homebrew/bin"
export PATH="$PATH:/opt/roc"

# opam configuration
[[ ! -r $HOME/.opam/opam-init/init.zsh ]] || source $HOME/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null
. "$HOME/.cargo/env"

export PATH=/Users/akhong/.volta/tools/image/node/20.13.1/bin:$PATH
export ANDROID_HOME="/Users/akhong/Library/Android/sdk"
export ANDROID_SDK_ROOT="/Users/akhong/Library/Android/sdk"
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH"
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export JAVA_HOME="/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home"
export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"

alias x86="$env /usr/bin/arch -x86_64 /bin/zsh ---login"
alias arm="$env /usr/bin/arch -arm64 /bin/zsh ---login"
