name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  coverage:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: hello
        uses: python:3.9
        with:
          entrypoint: echo
          args: "hello!"
